### ISSUE TITLE
Add drag & drop for todo items

### ISSUE THREAD

**Issue by alex-kim-dev** [alex-kim-dev/todo-app#1]
Some libs for react are listed here https://github.com/enaqx/awesome-react

Requirements:

- [x] keyboard, pointer, touch support
- [x] the height of the list item should be taken in account
- [x] to drag use: ~visual handle~ / ~modifier key~ / long press
- [ ] ~animate removing a todo?~
- [ ] add a test checking the changed order (failed)

**Comment by alex-kim-dev** [comment]
`react-dnd` seemed too complex.
Investigating `@dnd-kit` right now.
